[package]
name = "proj1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9"
base64 = "0.13.0"
clap = { version = "4.0", features = ["derive"] }